create table if not exists "user" (
  id integer generated by default as identity primary key,
  created_at timestamptz not null default now(),
  email varchar(256) unique,
  phone varchar(256) unique,
  password varchar(512) not null,
  role text not null check (role in ('admin', 'user')),
  user_name varchar(256) not null unique,
  is_logged boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists feedback (
  id integer generated by default as identity primary key,
  created_at timestamptz not null default now(),
  branch_name varchar(256) not null,
  customer_name varchar(256),
  emoji text not null check (emoji in ('Happy', 'Very Happy', 'Satisfied', 'Unsatisfied')),
  reason varchar(256),
  mobile_number varchar(256),
  updated_at timestamptz not null default now()
);

create table if not exists exported_feedbacks (
  id integer generated by default as identity primary key,
  created_at timestamptz not null default now(),
  feedback_url varchar(1000) not null,
  format varchar(256) not null,
  updated_at timestamptz not null default now(),
  user_id integer references "user"(id) on update cascade on delete set null
);

create index if not exists feedback_created_at_idx on feedback (created_at);
create index if not exists feedback_emoji_idx on feedback (emoji);
create index if not exists exported_feedbacks_user_id_idx on exported_feedbacks (user_id);
